### ISSUE TITLE
Game and editor crashes on shutdown

### ISSUE THREAD

**Issue by ueshita** [effekseer/EffekseerForGodot4#1]
The following Issue is the cause
- https://github.com/godotengine/godot-cpp/issues/889

This plugin uses the following Singleton
- Engine
- RenderingServer
- ResourceLoader

**Comment by saki7** [comment]
Could you propose this patch to upstream? I have personally tested this fix on my local repo, and it's working.
From my experience I'm not 100% sure if the SingletonBinder approach is technically correct or not, but we should be able to hear from core devs if we could submit this.

**Comment by ueshita** [comment]
It seems that godot-cpp 4.1 has addressed this issue fundamentally.
