### ISSUE TITLE
Error because of EditorInterface API change. - Godot 4.2

### ISSUE THREAD

**Issue by jmarceno** [effekseer/EffekseerForGodot4#4]
In Godot 4.2, Editor Interface is now a singleton.
This makes `plugin.gd `unable to register the icons, and the whole plugin does not load properly

Changing line 23 on `plugin.gd` from ,
`var theme = get_editor_interface().get_base_control().get_theme()`
to
`var theme = EditorInterface.get_editor_theme()`

Fixes the error and I´m able to use the use it again.
I have not experienced any other issues with 4.2

**Comment by ueshita** [comment]
This error has fixed.
https://github.com/effekseer/EffekseerForGodot4/releases/tag/1.70e.3
Thanks!
